version: '3.3'

services:

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  db:
    container_name: postgres
    image: postgres:12.0-alpine
    env_file:
      - ./.env.prod.db
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    container_name: nz01
    ports:
      - 80:80
    volumes:
      - static_volume:/home/banner_app/web/static
      - media_volume:/home/banner_app/web/media
    depends_on:
      - web

  web:
    build:
      context: ./banner_app
      dockerfile: Dockerfile.prod
    command: gunicorn banner_app.wsgi:application --timeout 500 --bind  0.0.0.0:8000 & celery -A banner_app worker -l info --loglevel=INFO -P solo --without-gossip --without-mingle --without-heartbeat
    container_name: web
    depends_on:
      - db
    expose:
      - "8000"
    volumes:
      - static_volume:/home/banner_app/web/static
      - media_volume:/home/banner_app/web/media
    env_file:
      - ./.env.prod

volumes:
  postgres_data:
  static_volume:
  media_volume:
