version: '3.3'

services:
  web:
    build:
      context: ./banner_app
      dockerfile: Dockerfile.prod
    command: gunicorn banner_app.wsgi:application --timeout 90 --bind  0.0.0.0:8000
    volumes:
      - static_volume:/home/banner_app/web/static
      - media_volume:/home/banner_app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  redis:
    image: "redis:alpine"
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/banner_app/web/static
      - media_volume:/home/banner_app/web/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
