version: '3.3'

services:
  nginx:
    build: ./nginx
    container_name: nz01
    ports:
      - 80:80
    volumes:
      - static_volume:/home/banner_app/web/static
      - media_volume:/home/banner_app/web/media
    depends_on:
      - web

  web:
    build:
      context: ./banner_app
      dockerfile: Dockerfile.prod
    depends_on:
      - db
    command: gunicorn banner_app.wsgi:application --timeout 500 --bind  0.0.0.0:8000
    volumes:
      - static_volume:/home/banner_app/web/static
      - media_volume:/home/banner_app/web/media
    expose:
      - 8000
    links:
      - redis
    env_file:
      - ./.env.prod

  db:
    container_name: pz01
    env_file:
      - ./.env.prod.db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"

  celery-worker1:
    build:
      context: ./banner_app
    container_name: celery-worker1
    hostname: worker1
    command: bash -c "celery -A banner_app worker -l info"
    volumes:
      - static_volume:/home/banner_app/web/static
      - media_volume:/home/banner_app/web/media
    depends_on:
      - redis

  celery-beat:
    build:
      context: ./banner_app
    container_name: celery-beat
    hostname: beat
    command: bash -c "celery -A banner_app beat -l info"
    volumes:
      - static_volume:/home/banner_app/web/static
      - media_volume:/home/banner_app/web/media
    depends_on:
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume:
