# Generated by Django 2.2.6 on 2019-10-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboardimage',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='billboards'),
        ),
    ]
