# Generated by Django 2.2.6 on 2019-10-28 09:48

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banner_detector', '0004_auto_20191028_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='banner_classes')),
                ('descriptor', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('banner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banner_detector.BannerType')),
            ],
        ),
        migrations.DeleteModel(
            name='BannerBaseImage',
        ),
    ]
