# Generated by Django 2.2.6 on 2019-10-28 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banner_detector', '0005_auto_20191028_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='basebanner',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
