# Generated by Django 2.2.6 on 2019-12-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_detector', '0005_auto_20191209_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannertype',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bannertype',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='banners'),
        ),
    ]
