# Generated by Django 2.2.6 on 2019-10-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_detector', '0006_basebanner_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboardimage',
            name='detected_image',
            field=models.ImageField(default='default.jpg', upload_to='billboards'),
        ),
    ]
