# Generated by Django 2.2.6 on 2019-12-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_detector', '0006_auto_20191219_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannertype',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='covers'),
        ),
    ]
