# Generated by Django 2.2.6 on 2020-03-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_detector', '0007_auto_20191219_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='stand_number',
            field=models.IntegerField(default=1),
        ),
    ]
