# Generated by Django 2.2.6 on 2019-11-01 19:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_detector', '0007_billboardimage_detected_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebanner',
            name='descriptor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
