# Generated by Django 2.2.6 on 2020-04-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_detector', '0008_bus_stand_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='stand_number',
        ),
        migrations.AlterField(
            model_name='bannertype',
            name='image',
            field=models.ImageField(default='default_poster.jpg', upload_to='covers'),
        ),
    ]
