# Generated by Django 2.2.6 on 2020-04-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_detector', '0009_auto_20200419_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillboardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(default=1)),
                ('name', models.CharField(default='Название', max_length=20)),
                ('description', models.CharField(default='Описание', max_length=100)),
            ],
        ),
    ]
