# Generated by Django 2.2.6 on 2019-11-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_detector', '0009_banner_closest_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='bus_number',
            new_name='number',
        ),
        migrations.AddField(
            model_name='bus',
            name='registration_number',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
