# Generated by Django 2.2.6 on 2020-04-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner_detector', '0010_billboardtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='stand_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banner_detector.BillboardType'),
        ),
    ]
