# Generated by Django 2.2.6 on 2020-04-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner_detector', '0011_bus_stand_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='stand_number',
            new_name='stand',
        ),
    ]
