# Generated by Django 2.2.6 on 2020-04-20 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner_detector', '0013_banner_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerobject',
            name='banner_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banner_detector.BannerType'),
        ),
    ]
